//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.02 at 02:28:39 PM KRAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ccfit.nsu.ru/schema/crack-hash-request", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.nsu.fit.crack.hash.crackhashmanager.dto.worker;
