spring:
  application:
    name: crack-hash-manager

# Настройки сервиса
application:
  number-workers: 1
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567"
  processing-time: 60 # Время в секундах
  size-queue: 10
  domain-workers:
    - "http://localhost:8081"
    - "http://localhost:8082"
