spring:
  application:
    name: crack-hash-manager
  data:
    mongodb:
      uri: mongodb://mongodb-1:27017,mongodb-2:27017,mongodb-3:27017/crack_hash_db?replicaSet=_replica_set_crack_hash&authSource=admin&readPreference=secondaryPreferred&w=majority
  rabbitmq:
    host: crack-hash-rabbitmq
    username: guest
    password: guest

# Настройки сервиса
application:
  number-workers: 1
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567"
  processing-time: 60 # Время в секундах
  size-queue: 10
  domain-workers:
    - "http://localhost:8081"
    - "http://localhost:8082"
  queue-name-producer: "crack-hash-request"
  queue-name-consumer: "crack-hash-response"
  exchange-name: "crack-hash-exchange"
  exchange-key-producer: "request-key"
  exchange-key-consumer: "response-key"

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
