spring:
  rabbitmq:
    host: crack-hash-rabbitmq
    username: guest
    password: guest

application:
  domain-manager: "http://localhost:8080"
  queue-name-consumer: "crack-hash-request"
  exchange-key: "response-key"
  exchange-name: "crack-hash-exchange"
